### ISSUE TITLE
can't figure out how to > splash:autoload(/path/to/my/local.js)

### ISSUE THREAD

**Issue by psychonaute** [scrapinghub/splash#1077]
I don't know much lua. 
I mounted a volume in my docker-compose.yml

```yml
    splash0:
        image: scrapinghub/splash:3.5
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        volumes:
            - ./js:/etc/splash/js:ro
```

but what path is pointing to my js folder?
i tried
`assert(splash:autoload{url='js/myscript.js'})`
`assert(splash:autoload{url='/etc/splash/js/myscript.js'})`
`assert(splash:autoload{url='./js/myscript.js'})`

 same with

`assert(splash:autoload("/etc/splash/js/myscript.js"))`
